class Jim
  @styles: Hash[String, String]

  attr_reader styles: Hash[String, String]

  DEFAULT_STYLES: {}

  def styles: (*untyped styles) -> Jim
  def add_style: (untyped property, *untyped values) -> Jim
  def rm_style: (untyped property) -> Jim
  def rm_styles: () -> Jim

  module LiquidFilters
    def jim_styles: (Jim jim, *untyped styles) -> Jim
    def jim_add_style: (Jim jim, untyped property, *untyped values) -> Jim
    def jim_rm_style: (Jim jim, untyped property) -> Jim
    def jim_rm_styles: (Jim jim) -> Jim
  end
end
