class Jim
  @format_setups: Hash[String, Hash[String, Integer? | String?]]

  DEFAULT_FORMAT_SETUPS: Hash[:Symbol, Hash[:Symbol, Integer | String]]

  def format_setups: (*untyped format_setups) -> Jim
  def add_format_setup: (untyped format, untyped setup) -> Jim
  def add_format_setting: (untyped format, untyped key, untyped value) -> Jim
  def reset_format_setups: () -> Jim

  module LiquidFilters
    def jim_format_setups: (Jim jim, *untyped format_setups) -> Jim
    def jim_add_format_setup: (Jim jim, untyped format, untyped setup) -> Jim
    def jim_add_format_setting: (Jim jim, untyped format, untyped key, untyped value) -> Jim
    def jim_reset_format_setups: (Jim jim) -> Jim
  end
end
