class Jim
  @watermark_src: String?
  @watermark_size: Float
  @watermark_x: Float
  @watermark_y: Float
  @watermark_opacity: Float

  attr_reader watermark_src: String?
  attr_reader watermark_size: Float
  attr_reader watermark_x: Float
  attr_reader watermark_y: Float
  attr_reader watermark_opacity: Float

  DEFAULT_WATERMARK_SRC: nil
  DEFAULT_WATERMARK_SIZE: Float
  DEFAULT_WATERMARK_X: Float
  DEFAULT_WATERMARK_Y: Float
  DEFAULT_WATERMARK_OPACITY: Float

  def watermark: (
			untyped watermark_src, ?untyped? watermark_size, ?untyped? watermark_x, ?untyped? watermark_y, ?untyped? watermark_opacity
		) -> Jim
  def watermark_src: (untyped watermark_src) -> Jim
  def watermark_size: (untyped watermark_size) -> Jim
  def watermark_x: (untyped watermark_x) -> Jim
  def watermark_y: (untyped watermark_y) -> Jim
  def watermark_opacity: (untyped watermark_opacity) -> Jim
  def rm_watermark: () -> Jim

  module LiquidFilters
    def jim_watermark: (
				Jim jim, untyped watermark_src, ?untyped? watermark_size, ?untyped? watermark_x, ?untyped? watermark_y, ?untyped? watermark_opacity
			) -> Jim
    def jim_watermark_src: (Jim jim, untyped watermark_src) -> Jim
    def jim_watermark_size: (Jim jim, untyped watermark_size) -> Jim
    def jim_watermark_x: (Jim jim, untyped watermark_x) -> Jim
    def jim_watermark_y: (Jim jim, untyped watermark_y) -> Jim
    def jim_watermark_opacity: (Jim jim, untyped watermark_opacity) -> Jim
    def jim_rm_watermark: (Jim jim) -> Jim
  end
end
