class Jim
  @widths: Array[Integer?]

  attr_reader widths: Array[Integer?]

  DEFAULT_WIDTHS: []

  def widths: (*untyped widths) -> Jim
  def add_width: (untyped width) -> Jim
  def rm_width: (untyped width) -> Jim
  def rm_widths: () -> Jim

  module LiquidFilters
    def jim_widths: (Jim jim, *untyped widths) -> Jim
    def jim_add_width: (Jim jim, untyped width) -> Jim
    def jim_rm_width: (Jim jim, untyped width) -> Jim
    def jim_rm_widths: (Jim jim) -> Jim
  end
end
