class Jim
  @filename_pattern: String
  @svg_filename_pattern: String?

  DEFAULT_FILENAME_PATTERN: String
  DEFAULT_SVG_FILENAME_PATTERN: String

  def filename_pattern: (untyped filename_pattern) -> Jim
  def svg_filename_pattern: (untyped svg_filename_pattern) -> Jim
  def filename_patterns: (untyped filename_pattern, untyped svg_filename_pattern) -> Jim

  module LiquidFilters
    def jim_filename_pattern: (Jim jim, untyped filename_pattern) -> Jim
    def jim_svg_filename_pattern: (Jim jim, untyped svg_filename_pattern) -> Jim
    def jim_filename_patterns: (Jim jim, untyped filename_pattern, untyped svg_filename_pattern) -> Jim
  end
end
