class Jim
  @src: String
  @alt: String?

  attr_reader src: String
  attr_reader alt: String?

  def initialize: (untyped src, ?untyped? alt, **untyped presets) -> Jim

  module LiquidFilters
    def jim_new: (untyped src, ?untyped? alt, *untyped presets) -> Jim
  end
end
