class Jim
  @nomarkdown: bool

  attr_reader nomarkdown: bool

  DEFAULT_NOMARKDOWN: bool

  def nomarkdown: (?untyped nomarkdown) -> Jim

  module LiquidFilters
    def jim_nomarkdown: (Jim jim, ?untyped nomarkdown) -> Jim
  end
end
