class Jim
  @img_attrs: Hash[String, String]

  DEFAULT_IMG_ATTRS: {}

  def img_attrs: (*untyped img_attrs) -> Jim
  def add_img_attr: (untyped key, untyped value) -> Jim
  def rm_img_attr: (untyped key) -> Jim
  def rm_img_attrs: () -> Jim

  module LiquidFilters
    def jim_img_attrs: (Jim jim, *untyped img_attrs) -> Jim
    def jim_add_img_attr: (Jim jim, untyped key, untyped value) -> Jim
    def jim_rm_img_attr: (Jim jim, untyped key) -> Jim
    def jim_rm_img_attrs: (Jim jim) -> Jim
  end
end
