class Jim
  @img_sizes: Hash[String, String]
	@default_img_size: String?

  DEFAULT_IMG_SIZES: {}
  DEFAULT_DEFAULT_IMG_SIZE: nil

  def img_sizes: (*untyped img_sizes) -> Jim
  def add_img_size: (untyped media_condition, untyped img_size) -> Jim
  def rm_img_size: (untyped media_condition) -> Jim
  def rm_img_sizes: () -> Jim
  def default_img_size: (untyped default_img_size) -> Jim
  def rm_default_img_size: () -> Jim

  module LiquidFilters
    def jim_img_sizes: (Jim jim, *untyped img_sizes) -> Jim
    def jim_add_img_size: (Jim jim, untyped media_condition, untyped img_size) -> Jim
    def jim_rm_img_size: (Jim jim, untyped media_condition) -> Jim
    def jim_rm_img_sizes: (Jim jim) -> Jim
    def jim_default_img_size: (Jim jim, untyped default_img_size) -> Jim
    def jim_rm_default_img_size: (Jim jim) -> Jim
  end
end
