class Jim
  @src: String
  @alt: String?

  def initialize: (untyped src, ?untyped? alt, *untyped presets, **untyped preset_options) -> Jim

  module LiquidFilters
    def jim_new: (untyped src, ?untyped? alt, *untyped presets) -> Jim
  end
end
