Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: false
Style/Lambda:
  Enabled: false

# Fix later
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
