class Jim::ResizedImage
  @source_filename: Pathname
  @source_blake3: String
  @resizing_width: Integer
  @resizing_height: Integer
  @watermark_filename: Pathname?
  @watermark_blake3: String?
  @watermark_width: Integer?
  @watermark_height: Integer?
  @watermark_x: Integer?
  @watermark_y: Integer?
  @watermark_opacity: Float?
  @watermark_is_valid: bool
  @image: Magick::Image?

  # needs source_image, resizing, watermark
  def initialize: (
			source_filename: Pathname, source_blake3: String,
			resizing_width: Integer, resizing_height: Integer,
			?watermark_filename: Pathname?, ?watermark_blake3: String?, ?watermark_width: Integer?, ?watermark_height: Integer?,
			?watermark_x: Integer?, ?watermark_y: Integer?, ?watermark_opacity: Float?, ?watermark_is_valid: bool
		) -> void
  def image: () -> Magick::Image
  def write: (
			output_extension: String, output_is_lossless: bool, output_quality: Integer, ?output_background: String?
		) -> Pathname
  def self.load_resized_image: (
			source_filename: Pathname, source_blake3: String, resizing_width: Integer, resizing_height: Integer
		) -> Magick::Image
end
