class Jim::SvgSourceImage
  @filename: Pathname
  @blake3: String
  @compressed: bool?

  XML_DECLARATION_REGEX: Regexp
  XML_DOCTYPE_REGEX: Regexp
  XML_COMMENT_REGEX: Regexp

  def initialize: (Pathname filename, String blake3) -> void
  def compressed?: () -> bool
  def convert: (bool compress) -> Pathname
  def convert_to_svg: () -> Pathname
  def convert_to_svgz: () -> Pathname
  def convert_to_inline_svg: () -> Pathname

  private

  def content: () -> String
  def svg_content: () -> String
  def svgz_content: () -> String
  def inline_svg_content: () -> String
  def ungzip: (String content) -> String
  def gzip: (String content) -> String
  def convert_to: (String extension, String content) -> Pathname
end
