module Jim::System
  @site_root_dir: String?
  @site_source_dir: String?
  @site: untyped
  @logger: untyped

  def self?.info: (?String tag, String text) -> void
  def self?.warn: (String text) -> void
  def self?.error: (String text) -> void
  def self?.config: () -> untyped
  def self?.path: (*String src) -> Pathname
  def self?.source_path: (*String src) -> Pathname
  def self?.destination_path: (*String src) -> Pathname
  def self?.local_cache_path: (*String src) -> Pathname
  def self?.cache_path: (*String src) -> Pathname
  def self?.render: (String? template_src, Hash[String, untyped] jim_context) -> String
  def self?.init: (untyped site, untyped logger) -> void

  # from Bridgetown/Jekyll implementations
  @site_destination_dir: Pathname?

  DEFAULT_TEMPLATE: String

  def self?.add_external_file: (Pathname source_filename, Pathname destination_filename) -> void
  def self?.read_template_file: (String template_src) -> String
end
