module Jim::Utils
  JSON_MODE: JSON::Ext::Generator::State
  LOSSLESS_MIME_TYPES: Array[String]
  SPRINTF_SUBSTITUTION_REGEX: Regexp
  SPRINTF_SUBSTITUTION_LIMIT: Integer

  def self?.deep_stringify_keys: (Hash[Object, Object] hash) -> Hash[String, Object]
  def self?.write_file: (Pathname filename, ?String content) ?{ (Pathname) -> void } -> Pathname
  def self?.write_file_if_not_exist: (Pathname filename, ?String content) ?{ (Pathname) -> void } -> Pathname
  def self?.read_json_file: (Pathname filename) -> Hash[Symbol, untyped]
  def self?.write_json_file: (Pathname filename, Hash[Symbol, untyped] content) -> Pathname
  def self?.load_image: (Pathname filename) -> Magick::Image
  def self?.color: (String? color) -> String
  def self?.mime_type: (Pathname | String filename) -> String?
  def self?.is_lossless_mime_type?: (String? mime_type) -> bool
  def self?.preferred_extension_for_mime_type: (String? mime_type) -> String?
  def self?.auto_convert_mime_type: (String? format) -> String?
  def self?.replace_filename_pattern: (
			String filename_pattern, Hash[Symbol, untyped] user_substitutions,
			source_sha256: String, source_extension: String, source_dirname: String, source_basename: String,
			resizing_width: Integer, resizing_height: Integer,
			output_extension: String, output_background: String?, output_is_lossless: bool, output_quality: Integer
		) -> Pathname
  def self?.tmp_filename: (Pathname filename) -> Pathname
  def self?.prepare_folder: (Pathname filename) -> void
  def self?.clean_dirname: (String dirname) -> String
  def self?.clean_basename: (String basename) -> String
  def self?.sprintf: (String format_string, **Hash[Symbol, untyped] substitutions) -> String
end
